### ISSUE TITLE
Unable to send/receive data

### ISSUE THREAD

**Issue by YoungsterJon** [mill1000/esphome-winix-c545#9]
New to ESPHome so not sure if I configured everything correctly but I followed the wiring as referenced in the photos.
I see all the controls in Home Assistant but they don't actually change the state of the machine.
Also sensor data like AQI or light intensity show up as Unknown.

Am I missing something?
[winix_c545.txt](https://github.com/mill1000/esphome-winix-c545/files/13865579/winix_c545.txt)

![esphomeHAControls](https://github.com/mill1000/esphome-winix-c545/assets/69780894/b70a7bdc-131f-4754-8426-5aa475bee8d7)
![PXL_20240108_193306512](https://github.com/mill1000/esphome-winix-c545/assets/69780894/d2a40194-9117-4da3-91cf-34c692534216)

**Comment by mill1000** [comment]
Hi. The wiring looks pretty good to me. Nothing obviously wrong.

1. Are you wiring the RESETn pin to ground as documented in the README?
2. Are you seeing anything in the device logs?
3. You can enable UART debugging to see if there's any traffic flowing.
e.g.
```yaml
uart:
  baud_rate: 115200
  debug:
    direction: BOTH
    after:
      delimiter: "\n"
    sequence:
      - lambda: UARTDebug::log_string(direction, bytes);
```
